### ISSUE TITLE
“2.4.5 全局内存访问的合并”中的语义不明

### ISSUE THREAD

**Issue by panda1234lee** [thegibook/revision#1]
《全局光照技术》
第二章 并行处理架构 
-- 2.4 GPU 并行计算架构
----2.4.5 全局内存访问的合并  P99
第二自然段中 "SMX中的线程每32个会被组成一个线程束（Thread wrap），每个线程束内的线程会被保证同步执行。"

这句话语义不明确，因为一个Warp内的线程应该都是并行的吧，它们都是针对不同数据执行同一指令，互不相关，所以此处应是“并行执行”

**Comment by ElvisQin** [comment]
感谢反馈，已修订
