### ISSUE TITLE
第12章 若干漏印、引用错误和容易产生歧义的地方

### ISSUE THREAD

**Issue by syaoming** [thegibook/revision#11]
- 第 817 页，公式（12.2）下的描述中，漏印了 κ。
- 第 825 页，第二段第 6 行的行文可能有误，“可以看做” 这一短句插入很生硬。同一句的后半部分表述有误，文中说是“沿光线方向的高斯分布“，这没有道理，我猜作者想要说的是”以光线为中心的高斯分布“。
- 第 826 页， 图片来自 [Crassin 2011] （Crassin 的 PhD 论文）， 而非 [Crassin et al., 2011]（Crassin 与 NVIDIA 的同事共同发表的论文）。本章还有若干图片的引用也出现了同样的错误，此处未列举。
- 第 826 页， a 与 b 图之间不是光线角度有差异，而是圆锥顶角角度有差异，文中的表述容易引起误解。
- 第 840 页，第一段第四行，”提升数据读取和纹理缓存效率” 表述有误，Crassin 原文表述的意思是 ”提升数据访问合并和纹理缓存效率“，这里"数据访问合并"（data access coalescing）是 GPU 计算中的概念，文中的翻译忽略了关键的 coalescing 。

**Comment by ElvisQin** [comment]
感谢反馈，已修订，综合评分10分
