### ISSUE TITLE
别字

### ISSUE THREAD

**Issue by zhangyi** [thegibook/revision#2]
原文================
1.2.1 阴影
在实时渲染领域，直接**关照**（Point light，Spot light以及Directional Light）。

建议================
关照似乎应为“光照”更为贴切吧。

**Comment by zhangyi** [comment]
原文================
1.2.4 间接光照
环境贴图仅用于光泽表面（Specular surface），对于完全粗糙表面（Diffuse surface）

疑惑================
Diffuse 译为弥漫的；散开的。Diffuse reflection译为漫反射，粗糙表面的话感觉译为 roughness surface似乎更为恰当，它产生的是漫反射（Diffuse reflection）

**Comment by zhangyi** [comment]
![image](https://user-images.githubusercontent.com/344059/33749140-12b065c4-dc07-11e7-89d8-981ffd8d8f9a.png)

单词 scattering 为散射的意思，漫反射是 Diffuse reflection

**Comment by ElvisQin** [comment]
感谢反馈，这部分内容为试读内容，正式版已发生改变
