### ISSUE TITLE
Ch1 P51

### ISSUE THREAD

**Issue by onamiforest** [thegibook/revision#28]
1.5.1.2 BRDF性质 这一小节中 把下标r作为入射而i作为出射 个人认为非常不妥，即不遵循这两个字母代表的英文原意，又不和书中前面的章节统一，这个变化十分突兀，不仔细看会造成很大的困扰。另外那个出射度B完全可以写成E（ωr）我这里的r指的是出射。这样可以和下面的E（ωi）风格一致，其含义更一目了然。

**Comment by onamiforest** [comment]
是能量守恒这部分

**Comment by onamiforest** [comment]
另外 这相当于针对该入射光照的出射度B这句话理解不能。。。是指上面这个函数？但根据公式1.48 这个B其实应该是出射光的E. 但是这句话里的“这”又是指什么呢？

**Comment by ElvisQin** [comment]
这个标注问题确实有点严重，主要是被维基百科那个配图带偏了，那个图用了下标r，当时该重新画一幅图就好了。
“这”指前一句的沿所有出射方向的积分，参见p15出射度（radiant exitance）的定义。

**Comment by onamiforest** [comment]
你是说维基百科的BRDF的图吗？个人觉得这个图画的挺对的啊，i为入射, r为出射。我个人觉得这个i代表就是代表indicent ，而r则是reflect 而且p49 p50都是按照这个逻辑写的，没啥问题啊，但是到了能量守恒这一章却把i r反了，不知为何。另外那个这字，我的理解你想说的是公式1.47，但是1.47却并不能表示出射度。。少了个L呢
