### ISSUE TITLE
若干文字错误

### ISSUE THREAD

**Issue by VoidPointer1986** [thegibook/revision#3]
28/223 图1.1… 图片来自PowderVR -> 图片来自PowerVR ?
33/223 个位置反射会空中 -> 个位置反射回空中 ?
从另一个地方反射会空中 -> 从另一个地方反射回空中 ?
但是在一个像素尺度上，它确是不光滑的 -> 但是在一个像素尺度上，它却是不光滑的?
55/223 这在计算机图形学中运用时分广泛 -> 这在计算机图形学中运用十分广泛
58/223 这些数据都是具有一定的分辨率（或者是按一定的采样率生成的数据） 语句不通顺?
原理表面 -> 远离表面?
它小于一个像素的尺寸 但是，但是大于光的波长 两个但是重复了?
65/223 但是只要找到这个分布函数，并能有效地计算光与表面的交互。 并能应该为就能?
67/223 所以导致表面上的每个点反射或折射光至多个不同的方向 折射光应为折射?
69/223 分别表示入射铅笔盒折射铅笔的几何范围 -> 分别表示入射铅笔和折射铅笔的几何范围 盒应该为和?
71/223 由于介质参数是随着波普变化的 -> 由于介质参数是随着波谱变化的 普->谱?
71/223 因此我们也常其为材质的特征光泽反射率 -> 因此我们也称其为材质的特征光泽反射率 ?
73/223 以及微面元法线发布函数 -> 以及微面元法线分布函数 ?
74/223 分析中分析中 -> 分析中 ?
通过后面最 Monte Carlo 积分的学习 -> 通过后面对 Monte Carlo 积分的学习
101/223 在指令遇到障碍是 -> 在指令遇到障碍时?
101/223 知道其相应条件满足指令才才继续前进 -> 直到其相应条件满足，指令才继续前进 知道->直到 才才 -> 才

**Comment by VoidPointer1986** [comment]
106/223 几乎不会有数据依赖光线  光线应该是管线?
110/223 另一个和GPU很像的特征是，它并且了常规处理器的多级缓存系统  并且 -> 摒弃?
111/223 因此，无论何时，所有处理器核看到的内存试图是完全一样的。  试图 -> 视图?
117/223 常量以及纹理内存其实只是全局内存的一中虚拟地址形式 一中 -> 一种?
117/223 而不但是从常量缓存上获取数据  而不但是 -> 而不是?
117/223 对于纹理内存，它好提供基于硬件的线性插值功能  它好 -> 它会?
118/223 所有使用共享内存需要⼩⼼处理存储体冲突  所有 -> 所以?
123/223 由于并行计算提成涉及大量的数据集 并行计算提成?
132/223 所有跟影响性能的因素几乎都跟一个称为过度绘制 所有跟影响性能的因素?
132/223 一般来说，要求得一个摄像机所能看到的  得一个 -> 对一个?
133/223 这是本质乃至着色管线基础架构的重要内容  不通顺?
137/223 虽然缓存可以在一定减少带宽导致的延迟  一定 -> 一定程度?
137/223 尽可能低将数据读取到寄存器  尽可能低 -> 尽可能地?
137/223 对其进行更多计算使用 -> 对其进行更多计算?
137/223 这种结局方案正是本章后面 结局 -> 解决?
137/223 这些方法的重点内容就是结局光源分配 结局 -> 解决?
144/223 并不能用简单地用树状结构进管理   并不能用 -> 并不能够?
144/223 即观察空间（view space）观察空间  重复?
145/223 它以分块着色的块在基础  在基础 -> 为基础?
162/223 SMAA采样一种适应性双阈值 采样 -> 采用?
175/223 YCgCo是一个压缩的颜色模型，能够与RGB之间进行无损的转换，但是YCgCo模型的其中一个维度是亮度  YCgCo -> YCoCg?
175/223 所以它能够直接在亮度方向  后面没写完?
176/223 每个像素可能包括多大七八个三角形图元 多大 -> 多达

**Comment by ElvisQin** [comment]
感谢反馈，已修订

**Comment by ElvisQin** [comment]
某些内容已在正式版修订，累积记5分
