### ISSUE TITLE
[P53] [P54] pencil应翻译为光锥

### ISSUE THREAD

**Issue by xiaodongyu** [thegibook/revision#37]
p53、54等页出现的入射“铅笔”、折射“铅笔”等应来自英文pencil，在这些语境中应翻译为“光锥”。
p54的“铅笔盒”应是拼音输入法带来的错误，应为“光锥和”
其他页面可能也有类似的误译，在电子文档中全部替换即可，不再一一列举。

**Comment by ElvisQin** [comment]
感谢反馈，已修正！

**Comment by Zieng** [comment]
看到作者对铅笔加了引号，还以为是故意用铅笔来形象化表述呢。
毕竟大部分人都在小时侯的科学课上观察过”弯曲的铅笔“的折射实验。
