### ISSUE TITLE
前言，本书中的逻辑 倒数第二段

### ISSUE THREAD

**Issue by gamestarjoren** [thegibook/revision#4]
以及动画电影公司（如皮克斯，迪斯尼等）。
-----》这个地方，个人觉得应该是描述为迪斯尼皮克斯更为妥当，因为皮克斯2006年已经是迪斯尼的子公司 了，不知兄意如何。

**Comment by ElvisQin** [comment]
这种情况，在一般的信息描述中通常只提及公司名字即可，一般涉及到版权方面的描述才会提及母公司之类的
