### ISSUE TITLE
关于antialiasing的翻译

### ISSUE THREAD

**Issue by boswelyu** [thegibook/revision#67]
本书中antialiasing翻译成了“反走样“。
好像我看过的很多其他教材上，antialiasing都会翻译成 “抗锯齿”。
个人感觉“抗锯齿”更容易接受一些。

**Comment by FancyVin** [comment]
反走样与走样成对出现，比抗锯齿更易理解吧。抗锯齿确实常见，但可能太白话了。

**Comment by boswelyu** [comment]
从这个角度看也确实是。或者是不是可以在本书中首次出现反走样的地方提一句：反走样，也叫抗锯齿。

说一下我自己的阅读感受，从头开始读这本书，第一个看到反走样的时候 ，我觉得反走样应该是在做防止或者纠正真实物体形状扭曲之类的事情，可能会比抗锯齿的内容更宽泛。直到后面看到出现antialiasing的时候，我才意识到原来本书中的反走样，其实就是抗锯齿。所以觉得如果一开始就能说明一下，会消除这个小误解。

**Comment by jacktheLad** [comment]
antialiasing翻译成【反走样】没问题的。
只要采样频率低于两倍 Nyquist frequency，就可以叫走样。
走样的表现不只是锯齿，还可能是摩尔纹，在时域上还可能是车轮效应。
锯齿只是走样的一种形式，所以反走样不一定是抗锯齿，也可能是抗摩尔纹，抗车轮效应等。
以上。

**Comment by Qinja** [comment]
同意楼上的见解（除了最后一行，一脚怼死）
走样范围更广，几何走样可以直观得到锯齿，但是着色走样和摩尔纹，车轮这种，都不会有明显的“锯齿”。

**Comment by boswelyu** [comment]
感谢解释，受教了。
