### ISSUE TITLE
【P211-213】表意不清：材质类型 or 材质类型组合？

### ISSUE THREAD

**Issue by sYeaLumin** [thegibook/revision#74]
P211中 

> 计算着色器分两步处理块中像素的着色计算：1. 对每个块执行材质类型定义（material classification） 2. 对每个材质类型分别执行一次计算着色器。

说的是定义每个块的【材质类型】并对每个【材质类型】分别执行一次计算着色器，但是看后面的解释感觉这里的意思又好像是：

> 定义块中每个像素的材质类型，得到这个块的【材质类型组合】，所有块都定义完之后，对每个【材质类型组合】分别执行一次计算着色器。

P212中倒数第5、6行文字

> 这里进一步的优化是将那些块内每个像素拥有完全一样材质类型组合的块使用的着色器的分支计算去掉，...

，单个像素只能有【材质类型】不能有【材质类型组合】吧？

P213第一行

> 场景中大部分块内每个像素都拥有相同的材质类型组合，即它们不包含分支处理

，这里的意思应该是块内所有的像素都是同一种材质类型，所以对应的着色器不包含分支处理。单个像素只能定义一种材质，所以应该是【材质类型】吧？与P212是同样的问题。

**Comment by ElvisQin** [comment]
最佳读者，阅读非常仔细，认真思考！祝学习进步！
